# Generated by Django 6.0.6 on 2026-06-14 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appestudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='ciclo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='elciclo', to='appestudiantes.ciclo'),
            preserve_default=False,
        ),
    ]
